### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by Yves57** [Yves57/AspNetCoreExt-Qos#9]
@DamianEdwards @davidfowl
Do you think is's a good idea to propose something like that directly in ASP.NET Core official distribution?
I think it would make sense in both Kestrel-only and IIS scenarios.

**Comment by davidfowl** [comment]
Yep, we've discussed things like this in the past but it's never been high enough priority to do it. Feel free to file an issue but we don't have any plans to do something like this or take this in the short term. The most we've discussed is doing a request queue middleware to limit the amount of concurrency for mostly poorly written apps at high load (like apps that call synchronous things).
